name: test_green
channels:
- defaults
dependencies:
- libprotobuf=3.2.0=0
- mkl=2017.0.1=0
- numpy=1.12.1=py36_0
- openssl=1.0.2l=0
- pandas=0.20.2=np112py36_0
- pip=9.0.1=py36_1
- protobuf=3.2.0=py36_0
- python=3.6.1=2
- python-dateutil=2.6.0=py36_0
- pytz=2017.2=py36_0
- pyyaml=3.12=py36_0
- readline=6.2=2
- setuptools=27.2.0=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- tensorflow=1.1.0=np112py36_0
- tk=8.5.18=0
- werkzeug=0.12.2=py36_0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - colorama==0.3.9
  - green==2.8.2
  - python-termstyle==0.1.10
  - unidecode==0.4.20

